# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

environment:
  # Server Configuration
  SERVER_TYPE: ""  # Can be "vLLM" or "NIM"
  SERVER_IMAGE: ""  # Path to server image
  SERVER_ARGS:
  SERVER_PORT: "8000"  # The port the server will listen on
  SERVER_HEALTH_CHECK_ENDPOINT: ""  # The endpoint to check if the server is ready
  SERVER_ENDPOINT: ""  # The endpoint for chat completions (e.g., "v1/chat/completions")
  
  # Model Configuration
  MODEL_NAME: ""
  MODEL_NAME_CLEANED: ""  # used in the benchmark result file name
  MODEL_TOKENIZER: ""  # matches the path of the tokenizer on the HF registry
  HF_TOKEN: ""  # Your Hugging Face API token

  # Benchmark Parameters
  MIN_REQUESTS: ""
  USE_CASES: ""
  CONCURRENCY_RANGE: ""
  REQUEST_MULTIPLIER: ""
  NUM_GPUS: ""  # Configure the number of GPUs to use (e.g., "1", "2", "4", "8")
  BENCHMARK_SERVER_IMAGE: "nvcr.io/nvidia/tritonserver:25.07-py3-sdk"  # Path to benchmark server image that contains genai-perf

  # Results Configuration
  RESULTS_PATH: ""  # Directory where benchmark results will be stored

# Service Account Configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Tolerations for pod scheduling
tolerations: []
# Example tolerations:
# - key: "dedicated"
#   operator: "Equal"
#   value: "user-workload"
#   effect: "NoSchedule"

# provided on startup automatically by NVCF
ngcImagePullSecretName: ""
ngcApiKeySecretName: ""
nvctNcaId: ""
nvctTaskId: ""
nvctTaskName: ""
nvctResultsDir: ""
nvctProgressFilePath: ""
